[package]
name = "binding_macros"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits", "fold"] }
quote = "1.0"
proc-macro2 = "1.0"
